отношение к врачу:
  - врач
  - доктор
  - хирург
  - терапевт
  - невролог
  - ортопед
  - уролог
  - гинеколог
  - специалист

отношение к записи и времени ожидания:
  - запись
  - время
  - ожидание
  - очередь
  - приём
  - направление
  - задержка
  - опоздание
  - регистрация

отношение к качеству лечения:
  - лечение
  - диагноз
  - операция
  - обследование
  - анализ
  - результат
  - консультация
  - помощь

отношение к организации:
  - организация
  - администрация
  - руководство
  - учреждение
  - центр
  - больница
  - клиника
  - госпиталь
  - оплата
  - стоимость
  - полис

отношение к пациенту:
  - внимание
  - отношение
  - пациент
  - обращение
  - забота
  - рекомендация

отношение к персоналу:
  - персонал
  - регистратура
  - оператор
  - бригада
  - коллектив
  - медсестра
  - администратор

отношение к условиям мед. учреждения:
  - палата
  - оборудование
  - чистота
  - корпус
  - территория
  - ремонт
  - туалет
  - питание
  - еда
  - парковка
  - санузел
  - душ
  - уборная
